### ISSUE TITLE
As a user, I would like the option to sort streaming services by prices

### ISSUE THREAD

**Issue by zaralouis** [kattawar/canitstreamtome#91]
The only options for sorting Streaming Services is alphabetically by title. However, I think it would be useful to be able to sort from highest to lowest prices and vice versa. 

<img width="1345" alt="screen shot 2018-04-11 at 1 03 15 pm" src="https://user-images.githubusercontent.com/14898278/38634650-ca4a0f90-3d88-11e8-94ad-2e6fa720ec81.png">

**Comment by erinjensby** [comment]
Unfortunately the prices are too different to be sortable. For example, many services are through cable provider or vary price per movie or have different prices for different levels of service.  Since there is not a clear way to sort this users can filter the data to show only certain types of pricing for services (e.g. Free, Through Cable Provider, Subscription, Renting services).
